### ISSUE TITLE
Used working in the Old windows 10 , clean build ran into following

### ISSUE THREAD

**Issue by cyrsis** [Kojoley/atari-py#1]
```bash
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-7c7iqed7-build\

(C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36) D:\TensorflowPY36CPU>pip install -U git+https
://github.com/Kojoley/atari-py.git
Collecting git+https://github.com/Kojoley/atari-py.git
  Cloning https://github.com/Kojoley/atari-py.git to c:\users\user\appdata\local\temp\pip-7zlbgeph-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\atari_py.egg-info
    writing pip-egg-info\atari_py.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\atari_py.egg-info\dependency_links.txt
    writing requirements to pip-egg-info\atari_py.egg-info\requires.txt
    writing top-level names to pip-egg-info\atari_py.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\atari_py.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-7zlbgeph-build\setup.py", line 92, in <module>
        tests_require=['nose2']
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\__init
__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\core.py", line 148, i
n setup
        dist.run_commands()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\dist.py", line 955, i
n run_commands
        self.run_command(cmd)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\dist.py", line 974, i
n run_command
        cmd_obj.run()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\egg_info.py", line 280, in run
        self.find_sources()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\egg_info.py", line 295, in find_sources
        mm.run()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\egg_info.py", line 526, in run
        self.add_defaults()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\egg_info.py", line 562, in add_defaults
        sdist.add_defaults(self)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\cmd.py", line 299, in
 get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\cmd.py", line 107, in
 ensure_finalized
        self.finalize_options()
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\build_ext.py", line 136, in finalize_options
        self.setup_shlib_compiler()
      File "C:\Users\user\AppData\Local\Temp\pip-7zlbgeph-build\setup.py", line 21, in setup_shlib_compiler
        _build_ext.setup_shlib_compiler(self)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\site-packages\setuptools\comman
d\build_ext.py", line 160, in setup_shlib_compiler
        compiler=self.compiler, dry_run=self.dry_run, force=self.force
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\ccompiler.py", line 1
031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\cygwinccompiler.py",
line 285, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36\lib\distutils\cygwinccompiler.py",
line 129, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-7zlbgeph-build\

(C:\Users\user\AppData\Local\Continuum\anaconda3\envs\TensorFlowGPU36) D:\TensorflowPY36CPU>
```
Please help

**Comment by Kojoley** [comment]
It looks like you have configured `distutils` to use `cygwin` but it is not installed in your system (or could not be found by distutils).
Fix your compilers/`distutils.cfg`, or just install the `atari_py` from the wheel (binaries). It should be as simple as typing ```pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py```

**Comment by Kojoley** [comment]
And report the problem to `setuptools`/`distutils`. The message you are getting looks cryptic and should be fixed in it.

**Comment by cyrsis** [comment]
pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py

Works like charm

U arent just good, you are really good
