### ISSUE TITLE
[help] image blinks when i run an atari game

### ISSUE THREAD

**Issue by yby9212** [Kojoley/atari-py#2]
import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
env.render()

Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x0000014FA81743C8>>
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\gym\envs\classic_control\rendering.py", line 347, in __del__
  File "D:\Python\Python36\lib\site-packages\gym\envs\classic_control\rendering.py", line 343, in close
  File "D:\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 304, in close
  File "D:\Python\Python36\lib\site-packages\pyglet\window\__init__.py", line 772, in close
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by Kojoley** [comment]
Try to read [the docs](https://gym.openai.com/docs/).

```python
import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
while True:
    env.step(env.action_space.sample())
    env.render('human')
```
