### ISSUE TITLE
Error on self.window.close() of rendering.py

### ISSUE THREAD

**Issue by yisuoyanyudeluzhou** [Kojoley/atari-py#4]
today i follow your answer of the question(https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows/43283856) to install successfully atari-py on win10, then run the simple example and appear the game screen as expected.

import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
for _ in range(1000):
    env.step(env.action_space.sample())
    env.render('human')

but when the program close the game screen i get the error message as the following;

Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x00000224A09F2AC8>>
Traceback (most recent call last):
  File "d:\Users\54516\Anaconda3\envs\dlwin36\lib\site-packages\gym\envs\classic_control\rendering.py", line 347, in __del__
  File "d:\Users\54516\Anaconda3\envs\dlwin36\lib\site-packages\gym\envs\classic_control\rendering.py", line 343, in close
  File "d:\Users\54516\Anaconda3\envs\dlwin36\lib\site-packages\pyglet\window\win32\__init__.py", line 305, in close
  File "d:\Users\54516\Anaconda3\envs\dlwin36\lib\site-packages\pyglet\window\__init__.py", line 770, in close
ImportError: sys.meta_path is None, Python is likely shutting down

what can i do to solve the problem? thanks

**Comment by Kojoley** [comment]
Does `env.close()` solve the problem for you?

```python
import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
for _ in range(1000):
    env.step(env.action_space.sample())
    env.render('human')
env.close()
```

**Comment by yisuoyanyudeluzhou** [comment]
yes, it's soled! thank you!
